### ISSUE TITLE
Can't load gh_sofistik.gha into GH

### ISSUE THREAD

**Issue by netsonicyxf** [SOFiSTiK/gh_sofistik#1]
When drag and drop the gh_sofistik.gha into main window of Grasshopper 0.9.76.0, it shows:
> The gh_sofistik Component Library was build against a different major version of the Grasshopper SDK: Local SDK = 1.0.0.20 Referenced SDK = 6. 7.18210.11281

**Comment by andreasniggl** [comment]
I assume, you are working with Rhino 6. Could you update your Rhino-Installation together with Grasshopper? The build-id of your Grasshopper indicates an inferior (probably pre-release) version. The Grasshopper shipped with Rhino 6 should have a major number of 1 (e.g. 1.0.0007 on my computer). With this, gh_sofistik.gha should load.

Please let me know, if the problem still exists.

Regards, Andreas

**Comment by netsonicyxf** [comment]
Is it possible to make it work with Grasshopper (0.9x) in Rhino 5?

**Comment by andreasniggl** [comment]
The binary is not working with GH 0.9x and Rhino 5. But you could try to build it for yourself linked against the dlls shipped with Rhino 5, however I have no idea how much adjustment this requires.
