### ISSUE TITLE
[question] Non-uniform line and area load

### ISSUE THREAD

**Issue by GonzaloNavarroMunoz** [SOFiSTiK/gh_sofistik#11]
Dear Developers,

First of all congrats for the latest releases, it getting extremely useful. 

I have a question about the "Line load" and "Area load" components, about a feature I'm not sure if it is implemented. Is it possible to define a non-uniform line load and area load with each respective component?

Thank you very much

Best regards, 

![image](https://user-images.githubusercontent.com/50489727/75269165-c497a580-57f8-11ea-8c56-af1d077e8bbf.png)

**Comment by andreasniggl** [comment]
Dear Gonzalo,

Good to hear, that you find it useful. Unfortunately, Line and area loads with varying values are currently not implemented. We will add your request to our wishlist.

Best regards,
Andreas
