### ISSUE TITLE
Line and area load projection in global Z

### ISSUE THREAD

**Issue by toretorp** [SOFiSTiK/gh_sofistik#12]
Hi,

I have been using your SOFiSTiK plug-in to create a FEM-model of a curved object. But I have a problem when using the line or area load function. As far as I can understand you have two options for the projection of the load; either using the local coordinate system (PX/PY/PZ) or using the global coordinate system with load value referenced to the line/element length/area (PXX/PYY/PZZ). But when you have a curved surface and you want to simulate for example snow load, you want to have the load in global direction with load value referenced to the projection length/area (PXP/PYP/PZP). Is there a function for this option in your plug-in?

**Comment by emanuelknapp** [comment]
Hi,

Sorry for the late response.
Unfortunately there is no such option in the plugin at the moment.
But what you could do, is to use the grasshopper "Replace Text" component
and replace for example "SAR 101 TYPE PZZ" with "SAR 101 TYPE PZP" in the SOFiLOAD output.
![grafik](https://user-images.githubusercontent.com/50671971/108193602-eed32900-7115-11eb-9723-2a975f4ef235.png)

I hope this solution helps.

With kind regards

Emanuel Knapp
