### ISSUE TITLE
Can't use SAR from trimmed surface in sofimshc

### ISSUE THREAD

**Issue by Leurmde** [SOFiSTiK/gh_sofistik#2]
The latest update suggests that trimmed breps are now supported.
When constructing a SAR from a trimmed brep, no error is given, however, passing it into the SOFiMSHC component results in an error:

> 1. Solution exception:Object reference not set to an instance of an object.

Regards,

Merijn

**Comment by Leurmde** [comment]
Alright, I found a solution/work-around. The problem seems to be in the use of the "surface split" component in grasshopper. When I create the same surface with the boundary surface component, instead of cutting holes out of a surface, there is no problem. 

Still wondering what's wrong with the srfSplit component though.

**Comment by andreasniggl** [comment]
Dear Merijn, I cannot reproduce the error with the 'surface split' component in grasshopper. Can you send me an example, that we can investigate the issue? 
Thank you, Andreas.

**Comment by Leurmde** [comment]
> Dear Merijn, I cannot reproduce the error with the 'surface split' component in grasshopper. Can you send me an example, that we can investigate the issue?
> Thank you, Andreas.

Hi Andreas,

The following example produces the error. (Had to zip the .gh file due to file-type restrictions).
This is the error:
![image](https://user-images.githubusercontent.com/36518983/57754766-827cf780-76ef-11e9-8c10-cb13f8ae9842.png)


[SOFiSTiK_ErrorMessage.zip](https://github.com/SOFiSTiK/gh_sofistik/files/3181244/SOFiSTiK_ErrorMessage.zip)

**Comment by andreasniggl** [comment]
Hi Merijn, 

Thank you for your immediate response and your example. Now I was able to reproduce the error and fixed it in the last commit.

Best, Andreas
