### ISSUE TITLE
Structural lines and structural points issue

### ISSUE THREAD

**Issue by GonzaloNavarroMunoz** [SOFiSTiK/gh_sofistik#3]
Dear Developer,

First of all, thanks for a great job, the components work very nicely. However, I have detected two issues or "bugs" in the latest version available of the gha file:

1- It is not possible to create a structural line with a variable cross-section with the "Structural Line" component by using the CADINP syntax "number of initial section" + "." + "number of the final section" (such as "1.2" indicating cross section number 1 at the beginning of the structural line and cross-section number 2 at its end). As can be seen in the image attached, only the first integer is read and written in the final CADINP code.
2-The SOFIMSHC component is not able to write the code associated with structural lines and structural points that are coincident in numeration if a coupling component between some structural points is added. The SOFIMSHC component acts not writing the code associated with the structural lines whose number is coincident with the number of a structural point, as can be seen in the images attached.

I hope I explained myself and that these issues could be solved as soon as possible. Don't hesitate to reply to me if something is not clear.

Thanks very much 

Gonzalo

![sno bug](https://user-images.githubusercontent.com/50489727/57573836-e8872780-742e-11e9-9617-a1af88f6dfcd.JPG)
![image](https://user-images.githubusercontent.com/50489727/57573894-a6aab100-742f-11e9-9697-5edba8da0c3c.png)
![image](https://user-images.githubusercontent.com/50489727/57573902-be823500-742f-11e9-8f8c-f9047df86f38.png)
![image](https://user-images.githubusercontent.com/50489727/57573912-d9ed4000-742f-11e9-9b99-9a1051ee1181.png)

**Comment by emanuelknapp** [comment]
Dear Gonzalo,

thank you a lot for your feedback. 
Both the issues you have mentioned got fixed in the last commits.

- Sections of Structural Lines now support the syntax "Number of beginning section"+"."+"Number of final section"
- A Structural Line and a Structural Point now can have the same Number (id) and get processed even when they are involved in a coupling

Best wishes

Emanuel
