### ISSUE TITLE
can't load gh_sofistik.gha into grasshopper

### ISSUE THREAD

**Issue by netsonicyxf** [SOFiSTiK/gh_sofistik#6]
The latest gh_sofistik.gha and grasshopper 1.0.0007 in Rhino 6 SR14.
It shows: 
![1](https://user-images.githubusercontent.com/43513391/58633722-ecb2b080-831b-11e9-9cd6-b202a05eef0c.png)

**Comment by andreasniggl** [comment]
Could be some version mismatch. I updated the assembly gh_sofistik.gha in github. Could you try it with the updated version? BR.

**Comment by netsonicyxf** [comment]
The updated version loads w/o error message.

**Comment by andreasniggl** [comment]
Ah good to hear. Regards.
