### ISSUE TITLE
gh_sofistik example

### ISSUE THREAD

**Issue by houda84** [SOFiSTiK/gh_sofistik#7]
Hi,

I was trying to execute gh_sofistik example, but I am getting an error in Sofilod part \ line load says ( +++++ error no. 902 in program SL_INITDatabase has no nodes defined. Any thoughts ?

Cheers,
Mahmoud

**Comment by andreasniggl** [comment]
Hi Mahmoud, before calculation the Sofiload part. Did you mesh the system? Are there any elements visible in the SOFiSTiK Animator, when opening the *.cdb?

**Comment by houda84** [comment]
![Animator 01](https://user-images.githubusercontent.com/52429360/60519088-1bd58c80-9ce3-11e9-8c1c-4255797d9729.PNG)
![Teddy 01](https://user-images.githubusercontent.com/52429360/60519089-1bd58c80-9ce3-11e9-8b80-9807e7d0b16c.PNG)
![WSP 01](https://user-images.githubusercontent.com/52429360/60519090-1bd58c80-9ce3-11e9-97e7-156291ed41e0.PNG)

Hi Aderea,
no actually I have nothing in my animator. please see my screen captures.

**Comment by andreasniggl** [comment]
Ah, you need to activate the meshing. See the input-parameter "Create Mesh" in the SOFIMSHC-node (which essentially generates a CTRL MESH 1 in the text output)
![meshing](https://user-images.githubusercontent.com/33835650/60521232-2b56d480-9ce7-11e9-88e1-b46ea6f6380e.JPG)

**Comment by houda84** [comment]
![GH NEW](https://user-images.githubusercontent.com/52429360/60534542-60bceb80-9d02-11e9-80cb-0e028a1b6fd5.PNG)
![aNIMATOR NEW](https://user-images.githubusercontent.com/52429360/60534661-9feb3c80-9d02-11e9-98e3-c5093489f90d.PNG)

Hi Andrea,
Thanks for your prompt reply. works like charm. I had to replace the sofimshc component with a new one in grasshopper example.
Cheers,
Mahmoud
