### ISSUE TITLE
Flipping local z-axis

### ISSUE THREAD

**Issue by toretorp** [SOFiSTiK/gh_sofistik#8]
Hi! I am using the sofistik/grasshopper plugin to create a FEM-model. I want to flip the direction of the local z-axis on one of the walls, but when I try to do that in grasshopper (using the flip z function for structural areas) nothing is happening. Anybody that know how I can solve this?

![2020-01-09 15_45_23-Window](https://user-images.githubusercontent.com/59576262/72077237-35413c00-32f7-11ea-80e0-f875ecbb5255.png)

**Comment by andreasniggl** [comment]
There is a but in the 'Flip Z' parameter causing that the orientation is not being transferred to SOFiSTiK correctly. We are going to fix this. As a workaround, you can set the normal direction manually through the parameter User Text using CADINP Language (NX,NY,NZ). Please be aware, that the normal direction being passed here is opposite to the normals of the quad elements.
